import os


class Config(object):
    SQLALCHEMY_USERNAME = os.getenv('SQLALCHEMY_USERNAME')
    SQLALCHEMY_PASSWORD = os.getenv('SQLALCHEMY_PASSWORD')
    SQLALCHEMY_DB = 'series'
    SQLALCHEMY_DATABASE_URI = f'postgresql://{SQLALCHEMY_USERNAME}:{SQLALCHEMY_PASSWORD}@localhost:5432/{SQLALCHEMY_DB}'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = False
