"""Added universe and universe_show table

Revision ID: 3cad944cc8c5
Revises: 666efb294be2
Create Date: 2019-08-21 16:27:05.485833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3cad944cc8c5'
down_revision = '666efb294be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universe',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('summary', sa.String(), nullable=True),
                    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
                    sa.Column('ModifiedBy', sa.String(), nullable=True),
                    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
                    sa.Column('CreatedBy', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('universe_shows',
                    sa.Column('universe_id', sa.Integer(), nullable=True),
                    sa.Column('show_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
                    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universe_shows')
    op.drop_table('universe')
    # ### end Alembic commands ###
