"""Adding Movie and MovieGroups tables

Revision ID: 3f70601b0970
Revises: 3cad944cc8c5
Create Date: 2020-05-10 12:42:24.981928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f70601b0970'
down_revision = '3cad944cc8c5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.String(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('added_movie',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.String(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.create_table('movie_groups_movies',
    sa.Column('movie_group_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_group_id'], ['movie_groups.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_groups_movies')
    op.drop_table('added_movie')
    op.drop_table('movie_groups')
    # ### end Alembic commands ###
