"""Added run_time to episodes table

Revision ID: 666efb294be2
Revises: 
Create Date: 2019-07-15 10:40:10.284177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '666efb294be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('run_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'run_time')
    # ### end Alembic commands ###
